### ISSUE TITLE
Decide what to do about debug strings and 3.7

### ISSUE THREAD

**Issue by gusmonod** [bloomberg/pystack#90]
As this [comment][comm] says, the debug format in f-strings were [introduced in 3.8][docs]. We should decide what to do about it as PyStack officially supports 3.7 and therefore should be able to run in 3.7. Options that I can think of:

1. Degrade the `__repr__` output in 3.7, same in other versions
2. Reimplement same output with 3.7+ compliant features
3. Remove the enhanced output altogether

[comm]: https://github.com/bloomberg/pystack/commit/e11db2325c5913b8de3107119a10058a43554f1a#r110643796
[docs]: https://docs.python.org/3/whatsnew/3.8.html#bpo-36817-whatsnew

**Comment by gusmonod** [comment]
Fixed by #92

**Comment by 3ok** [comment]
Quick question about this.

It seems that the `1.0.1` release has this Python 3.8 debug f-string issue, but it is still [installable for Python 3.7 users](https://pypi.org/project/pystack/1.0.1/#files) so they would have to explicitly do `pip install pystack==1.0.0` instead of `pip install pystack` to avoid getting the `1.0.1` release.

What do you think the best approach is here?
- yank `1.0.1` and release a `1.0.2` version with the above fix
- keep it as-is (either ways Python 3.7 is EoL in a few weeks, not sure if you are going to support it after that?)
- other?

**Comment by godlygeek** [comment]
Mm. We are going to drop 3.7 support, but you're right, ideally the last installable version for 3.7 should actually work in 3.7, and we should do one of these two options. I lean towards releasing a 1.0.2 that supports 3.7, I think.

**Comment by godlygeek** [comment]
This fixed in the 1.1.0 release.
